repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        exclude:  data|.ipynb$
    -   id: end-of-file-fixer
        exclude:  data|.ipynb$
    -   id: check-yaml
    -   id: check-added-large-files
# TODO dvp: return rstcheck, fix docs files for that
#-   repo: https://github.com/myint/rstcheck
#    rev: 3f92957
#    hooks:
#    -   id: rstcheck
-   repo: local
    hooks:
    -   id: isort
        name: isort
        exclude: dev|\.idea|\.cache
        entry: poetry run isort
        language: system
        types: [python]
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
