# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - path: .
