[tool.poetry]
name = "mckit"
version = "1.5.0"
description = "Tools to process MCNP models and results"
authors = ["rrn <r.rodionov@iterrf.ru>"]
maintainers = ["dpv2015 <dmitri_portnov@yahoo.com>"]
homepage = "https://github.com/rorni/mckit"
repository = "https://github.com/rorni/mckit"
keywords = ["mckit", "MCNP"]
build = "build.py"

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
attrs = "^20.2.0"
click-loguru = "^1.3.4"
click-log = "^0.3.2"
mkl-devel = "^2018.0.3"
numpy = "^1.19.4"
sly = "^0.4"
scipy = "^1.5.3"
tomlkit = "^0.7.0"
DateTime = "^4.3"
nlopt = "^2.6.2"
colorama = "^0.4.4"
atomicwrites = "^1.4.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
nox = "^2020.8.22"
pytest-benchmark = "^3.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
mckit = "mckit.cli.runner:mckit"
