[tool.poetry]
name = "mckit"
version = "0.4.5-alpha.0"
description = "Tools to process MCNP models and results"
authors = ["rrn <r.rodionov@iterrf.ru>"]
maintainers = ["dpv2015 <dmitri_portnov@yahoo.com>"]
homepage = "https://github.com/rorni/mckit"
repository = "https://github.com/rorni/mckit"
license = "MIT"
keywords = ["mckit", "MCNP"]
build = "build.py"
documentation = "https://mckit.readthedocs.io"
# Select from PyPI classifiers: https://pypi.org/classifiers/
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: C",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering :: Physics",
]

[tool.poetry.dependencies]
python = "^3.7"
DateTime = "^4.3"
Pygments = "^2.7.2"
atomicwrites = "^1.4.0"
attrs = "^20.2.0"
click = "^7.1.2"
click-loguru = "^1.3.4"
colorama = "^0.4.4"
importlib-metadata = {version = "^2.0.0", python = "<3.8"}
numpy = "^1.19.4"
numpydoc = "^1.1.0"
ply = "^3.11"
scipy = "^1.5.3"
sly = "^0.4"
tomlkit = "^0.7.0"
toolz = "^0.11.1"
tqdm = "^4.53.0"
asyncio = "^3.4.3"
aiofile = "^3.3.3"
mkl = "^2019.0"
mkl-include = "^2019.0"

[tool.poetry.dev-dependencies]
Pygments = "^2.7.2"
Sphinx = "^3.3.0"
black = "^20.8b1"
codecov = "^2.1.10"
coverage = "^5.3"
darglint = "^1.5.5"
flake8 = "^3.8.4"
flake8-annotations = "^2.4.1"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.1"
flake8-bugbear = "^20.1.4"
flake8-docstrings = "^1.5.0"
flake8-import-order = "^0.18.1"
mypy = "^0.790"
nox = "^2020.8.22"
numpydoc = "^1.1.0"
pre-commit = "^2.8.2"
pytest = "^6.1.2"
pytest-benchmark = "^3.2.3"
pytest-cov = "^2.10.1"
pytest-mock = "^3.3.1"
reorder-python-imports = "^2.3.6"
safety = "^1.9.0"
sphinx-autodoc-typehints = "^1.11.1"
sphinx-autorun = "^1.1.1"
sphinx-rtd-theme = "^0.5.0"
sphinxcontrib-napoleon = "^0.7"
xdoctest = "^0.15.0"
wheel = "^0.35.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry>=1.0.0", "setuptools", "wheel", "setuptools-cpp"]

[tool.poetry.scripts]
mckit = "mckit.cli.runner:mckit"

[tool.coverage.paths]
source = ["mckit", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["mckit"]

[tool.coverage.report]
show_missing = true
# fail_under = 100  # So far, this is just a dream.

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/rorni/mckit/issues"
