[tool.poetry]
name = "mckit"
version = "1.5.0"
description = "Tools to process MCNP models and results"
authors = ["rrn <r.rodionov@iterrf.ru>"]
maintainers = ["dpv2015 <dmitri_portnov@yahoo.com>"]
homepage = "https://github.com/rorni/mckit"
repository = "https://github.com/rorni/mckit"
keywords = ["mckit", "MCNP"]
build = "build.py"

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
attrs = "^20.2.0"
click-loguru = "^1.3.4"
click-log = "^0.3.2"
numpy = "^1.19.4"
sly = "^0.4"
scipy = "^1.5.3"
tomlkit = "^0.7.0"
DateTime = "^4.3"
colorama = "^0.4.4"
atomicwrites = "^1.4.0"
mkl-devel = "^2018.0.3"
toolz = "^0.11.1"
ply = "^3.11"
pytest-mock = "^3.3.1"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
nox = "^2020.8.22"
pytest-benchmark = "^3.2.3"
Sphinx = "^3.3.0"
coverage = "^5.3"
reorder-python-imports = "^2.3.6"
black = "^20.8b1"
flake8 = "^3.8.4"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.1"
flake8-bugbear = "^20.1.4"
flake8-import-order = "^0.18.1"
safety = "^1.9.0"
pre-commit = "^2.8.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry>=1.0.0", "setuptools", "wheel", "setuptools-cpp"]

[tool.poetry.scripts]
mckit = "mckit.cli.runner:mckit"

[tool.coverage.paths]
source = ["mckit", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["mckit"]

[tool.coverage.report]
show_missing = true
# fail_under = 100  # So far, this is just a dream.
