[build-system]
build-backend = "scikit_build_core.build"
requires = [ "numpy", "scikit-build-core>=0.12" ]

[project]
name = "mckit"
version = "0.9.0"
description = "Tools to process MCNP models and results"
readme = "README.rst"
keywords = [ "mckit", "MCNP" ]
license = "MIT"
requires-python = ">=3.12"
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: C",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering :: Physics",
]
[[project.authors]]
name = "rrn"
[[project.maintainers]]
email = "dmitri_portnov@yahoo.com"
name = "dvp2015"
[project.scripts]
mckit = "mckit.cli.runner:mckit"
[project.urls]
Documentation = "https://mckit.readthedocs.io"
Homepage = "https://github.com/MC-kit/mckit"
Issues = "https://github.com/MC-kit/mckit/issues"
Repository = "https://github.com/MC-kit/mckit"

[dependency-groups]
analyze = [ "jupyterlab>=4.5", "jupytext>=1.19" ]

# pixi example: https://github.com/prefix-dev/pixi/blob/main/examples/pybind11/pyproject.toml
[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build/{wheel_tag}"
[tool.scikit-build.build]
verbose = true
[tool.scikit-build.cmake]
build-type = "Release"
source-dir = "."
[tool.scikit-build.logging]
level = "INFO"
[tool.scikit-build.wheel]
packages = [ "src/mckit" ]
exclude = [ "**/__pycache__", "**/*.pyc" ]

[tool.pixi.dependencies]
click = "*"
loguru = "*"
mkl-devel = ">=2026.0.0,<2027"
nlopt = ">=2.9"
numpy = ">=2.4"
ply = "*"
python = "*"
sly = "*"
tomli-w = "*"
[tool.pixi.environments]
analyze = { features = [ "analyze" ], solve-group = "default" }
default = { features = [ "build", "test", "style" ], solve-group = "default" }
docs = { features = [ "build", "docs" ], solve-group = "default" }
prod = { solve-group = "default" }
py312 = { features = [ "build", "py312", "test" ] }
py313 = { features = [ "build", "py313", "test" ] }
py314 = { features = [ "build", "py314", "test" ] }
publish314 = { features = [ "build", "py314", "publish314"], solve-group = "default"}
#pypi = { features = [ "pypi" ], solve-group = "default" }
typeguard = { features = [ "typeguard", "test" ], solve-group = "default" }
[tool.pixi.feature]
py312.dependencies.python = "3.12.*"
py313.dependencies.python = "3.13.*"
py314.dependencies.python = "3.14.*"
#pypi.tasks.pypi_build = "pixi run uv build --no-build-isolation"
#pypi.tasks.repairwheel = "repairwheel -l .pixi/envs/default/lib -o fixed-wheels dist/*.whl"
[tool.pixi.feature.build.dependencies]
# Explicitly add build tools for faster resolution
cmake = ">=4"
ninja = "*"
scikit-build-core = ">=0.12"
#uv = ">=0.11.25,<0.12"
pysocks = ">=1.7.1,<2"
[tool.pixi.feature.docs.dependencies]
esbonio = ">=2"
# rstcheck[sphinx,toml]>=6.2.5",
sphinx = ">=9.1"
sphinx-autobuild = ">=2025.8.25"
sphinx-autodoc-typehints = ">=3.10"
sphinx-click = ">=6.2.0"
[tool.pixi.feature.docs.tasks]
docs = { cmd="sphinx-autobuild --open-browser docs/source docs/_build",  description="Preview the edited docs in a browser." }
docs-build = { cmd="sphinx-build docs/source docs/build",  description = "Build the docs in docs/build folder." }
[tool.pixi.feature.style.dependencies]
pylint = ">=4.0.6,<5"
mypy = ">=2.1.0"
pre_commit = ">=4.3"
pyright = ">=1.1.406"
ruff = ">=0.15"
ty = ">=0.0.55"
pyrefly = ">=1.1.1"
basedpyright = ">=1.39.8"
[tool.pixi.feature.style.tasks]
mypy = "mypy src"
pre-commit = "pre-commit run --show-diff-on-failure --color=always --all-files"
pylint = "pylint --recursive=y src tests"
pyright = "pyright"
basedpyright = "basedpyright"
ruff = { cmd = [ "ruff check --fix src tests", "ruff format src tests" ] }
[tool.pixi.feature.test.dependencies]
pytest = ">=9.0.3"
pytest-cov = ">=7.1.0"
pytest-benchmark = ">=5.2.3"
pytest-mock = ">=3.15.1"
pytest-xdist = ">=3.8.0"
psutil = ">=7.2.2"
xdoctest = ">=1.3.2"
[tool.pixi.feature.test.tasks]
test-fast = { cmd = "pytest -m 'not slow'", description = "Run fast test" }
test-slow = { cmd = "pytest -m 'slow'", description = "Run slow test (if test-fast passed)" }
test = { cmd = "pytest", description = "Run all the tests." }
coverage = { cmd = "pytest --cov --cov-report=term-missing:skip-covered", description = "Run tests with coverage" }
coverage-html = { cmd = "pytest --cov --cov-report html:htmlcov && open htmlcov/index.html", description = "Run tests with coverage and open results in a browser" }
[tool.pixi.feature.typeguard.dependencies]
typeguard = ">=4.5"
[tool.pixi.feature.typeguard.tasks]
typeguard = { cmd = "pytest --typeguard-packages=src", description = "Run dynamic type cheks on testing." }
[tool.pixi.feature.publish314.tasks]
publish314 = { cmd = "pixi publish -vvv --target-channel .output-3.14", description = "Publish for python-3.14" }
[tool.pixi.package]
host-dependencies.mkl-devel = ">=2026"
host-dependencies.nlopt = "*"
host-dependencies.numpy = "*"
host-dependencies.scikit-build-core = ">=0.12"
name = "mckit"
version = "0.9.0"
[tool.pixi.package.build-dependencies]
scikit-build-core = ">=0.12.1"
#python="==3.14.6"  # no freethreaded
[tool.pixi.package.build.backend]
name = "pixi-build-python"
version = "*"
#[tool.pixi.package.run-dependencies]
#python="==3.14.6"  # no freethreaded
#click = ">=8.3"
#loguru = ">=0.7"
#mkl-devel = ">=2026"
#nlopt = "*"
#numpy = "*"
#ply = ">=3.11"
#sly = ">=0.5"
#tomli-w = ">=1.2"
[tool.pixi.pypi-dependencies]
mckit = { path = ".", editable = true }
[tool.pixi.pypi-options]
no-build-isolation = [ "mckit" ]
[tool.pixi.workspace]
channels = [ "conda-forge" ]
platforms = [ "linux-64", "win-64" ]
# channels = ["https://prefix.dev/conda-forge"] - 2026-05-06 - timeout
conda-pypi-map = false  # fix: pixi failed to load conda-pypi map - timeout
requires-pixi = ">=0.70.2"
preview = [ "pixi-build" ]

#[tool.uv.extra-build-dependencies]
#mckit = [ "scikit_build_core" ]

[tool.mypy]
files = "src/**/*.py"
exclude = """  (?x)(
  parser.py$  # mypy doesn't like parser code
| _tab.py$    # ...
| lexer.py$   # ...
  )
"""
# namespace_packages = true
follow_imports = "silent"
python_version = "3.14"
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
disable_error_code = [ "annotation-unchecked" ]
enable_error_code = [ "ignore-without-code", "redundant-expr", "truthy-bool" ]
# strict = true  # TODO dvp: uncomment this to get strict control
show_error_context = true
pretty = true
error_summary = true
cache_dir = ".cache/mypy"
warn_unused_configs = true
show_error_codes = true

[[tool.mypy.overrides]]
module = [ "tomllib" ]
allow_redefinition = true
disable_error_code = "no-redef"

[tool.coverage.paths]
source = [ "src" ]
[tool.coverage.report]
exclude_lines = [
  "def __repr__",
  "if __name__ == .__main__.:",
  "if 0:",
  "if TYPE_CHECKING:",
  "if self.debug",
  "pragma: no cover",
  "raise AssertionError",
  "raise NotImplementedError",
]
fail_under = 90  # TODO dvp: increase limit to 100 with code maturing
ignore_errors = true
omit = [ "**/__init__.py", "*_tab.py" ]
show_missing = true
skip_covered = true
sort = "Cover"
[tool.coverage.run]
branch = true
omit = [ "**/__init__.py", "*_tab.py", "tools/*.py" ]
parallel = true
source = [ "src" ]

[tool.xdoctest]
options = ""
quiet = true

[tool.jupytext]
# https://jupytext.readthedocs.io/en/latest/config.html
# Pair ipynb notebooks to py:percent text notebooks
formats = "ipynb,py:percent"

[tool.creosote]
deps-file = "pyproject.toml"
exclude-deps = [ "intel-cmplr-lib-ur", "mkl-devel", "python-dotenv", "tomli", "tqdm", "typer" ]
paths = [ "adhoc", "src" ]
sections = [ "project.dependencies" ]
venvs = [ ".pixi/envs/analyze", ".pixi/envs/default", ".pixi/envs/docs" ]

[tool.rstcheck]
ignore_messages = '(Unknown directive type "(todo.*|automodule)".$)'
report_level = "ERROR"
