meshtal : header title nps _NL tallies

_NL: CR? LF

header : "mcnp" "version" stamp "mpi"? "ld=" stamp "probid =" stamp stamp _NL

?stamp: STAMP

title: EVERYTHING _NL

EVERYTHING.-10: /[^\n]+/

nps: _NPS_LABEL float _NL

_NPS_LABEL: "Number of histories used for normalizing tallies ="

float: SIGNED_FLOAT | INT   

tallies: [_NL* tally]+ _NL+

tally.10: tally_header _NL boundaries _NL data

tally_header: _MESH_TALLY_NUMBER_LABEL int _NL [title] particle

_MESH_TALLY_NUMBER_LABEL: "Mesh Tally Number"

int: INT  // postive only

particle: _PARTICLE_LABEL KIND "mesh tally." _NL

_PARTICLE_LABEL: /This is an?/

boundaries: _BOUNDARIES_LABEL _NL [cylinder] bins

_BOUNDARIES_LABEL: "Tally bin boundaries:"

cylinder: _CYLINDER_LABEL  vector ", axis in"  vector "direction" _NL

_CYLINDER_LABEL: "Cylinder origin at"

vector: float+

bins: direction _NL direction _NL direction _NL energies _NL

direction: _DIRECTION_THETA_LABEL vector -> direction_theta
         | XYZR "direction:" vector -> direction_xyzr

_DIRECTION_THETA_LABEL: "Theta direction (revolutions):"

XYZR: "X" | "Y"  | "Z" | "R"

energies: _ENERGIES_LABEL vector -> energies_e
        | "Time:" vector -> energies_t

_ENERGIES_LABEL: "Energy bin boundaries:"

data: matrix_data
    | column_data _NL?

matrix_data: energy_bins [_NL+ total_energy_bin]

energy_bins: energy_bin (_NL _NL _NL _NL energy_bin)* _NL?

energy_bin: _ENERGY_BIN_LABEL float "-" float "MeV" _NL _NL spatial_bins -> energy_bin_e
          | "Time:" float _NL+ spatial_bins -> energy_bin_t

_ENERGY_BIN_LABEL: "Energy Bin:"

// spatial_bins: spatial_bin (_NL _NL spatial_bin)* (_NL _NL _NL)?

spatial_bins: spatial_bin (_NL _NL spatial_bin)* (_NL _NL)? 

spatial_bin: dir_spec "bin:" float "-" float _NL _NL \
             /Tally Results:  .*/ _NL matrix _NL   \
             "Relative Errors" _NL matrix

dir_spec.-10: DIR_SPEC

DIR_SPEC: XYZR | "Th"

total_energy_bin: _TOTAL_ENERGY_BIN_LABEL _NL spatial_bins _NL

_TOTAL_ENERGY_BIN_LABEL: "Total Energy Bin"

column_data: column_header matrix [total_matrix]

matrix : vector (_NL vector)* _NL?

total_matrix: _TOTAL vector ( _NL _TOTAL vector)* _NL?

_TOTAL: "Total"

column_header : [energy] dir_spec dir_spec dir_spec "Result" "Rel Error" _NL

?energy: "Energy"

KIND: "neutron"|"photon"|"electron"

// MCNP version idenficiation entry on title line
STAMP: /[0-9\/:]+/

// Numbers
%import common.SIGNED_FLOAT
%import common.INT
// Separators / new line (used)
%import common.NEWLINE
%import common.CR
%import common.LF
// Separators / whitespace (ignored)
%import common.WS_INLINE
%ignore WS_INLINE
