name: Build and publish on PyPI

on:
  release:
    types:
      - published

  workflow_dispatch:  # TODO: debug only


permissions:
  contents: read  # Minimal required permissions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/master' || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # ubuntu-20.04 is required to build wheels for older OS (clusters...)
        os: ['ubuntu-20.04', 'ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.12', '3.13', '3.14']
        exclude:
          - os: 'macos-latest'
            python-version: '3.14'   # TODO 'ply' error
    steps:
    - name: Check out the repository
      uses: actions/checkout@v7
      with:
        fetch-depth: 1
        submodules: 'true'

    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      with:
        platforms: all

    - name: Build wheels    
      uses: pypa/cibuildwheel@v4.2.1
      
    - uses: actions/upload-artifact@v7
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ matrix.python-version }}
        path: ./wheelhouse/*.whl          

  publish:
    needs: build          
    runs-on: 'ubuntu-latest'
    steps:
    - name: 📦 Install uv
      uses: astral-sh/setup-uv@v10
      with:
        python-version: 3.14
        enable-cache: true
        cache-dependency-glob: |
          **/uv.lock
          **/pyproject.toml
    - uses: actions/download-artifact@v8
      with:
        pattern: cibw-wheels-*
        path: ./wheelhouse          

    - name: 📦 Build src package
      run: |
        uv build --sdist

    - name: 📤 Publish package on PyPI
      if: ${{ !github.event.act }} # skip during local actions testing
      run: uv publish \
        --username=__token__ \
        --password=${{ secrets.PYPI_TOKEN }} \
        "wheelhouse/*.whl" \
        dist/*.tar.gz \
        --check-url https://pypi.org/simple \
        --trusted-publishing always
