name: Build and publish on PyPI

on:
  release:
    types:
      - published
    branches:
      - main
      - master
#on:
#  push:
#    tags:
#      - 'v*.*.*'


jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
# TODO dvp: return MacOS support when MKL does, see issue on github
#        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Checkout submodules
        run: git submodule update --init --recursive --depth=1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version
          poetry version

      - name: Build wheel
        run: |
          poetry install --no-dev --no-root
          poetry build -f wheel

      - name: Build sdist
        run:  poetry build -f sdist
        if:   matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'

      - name: Publish package for ${{ matrix.os }}, python ${{ matrix.python-version }}
        run:  poetry publish  -u __token__ -p ${{ secrets.PYPI_TOKEN }}
