name: Build and publish on PyPI

on:
  release:
    types:
      - published
    branches:
      - main
      - master
  push:
    tags:
      - 'v*'


jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # The ubuntu-20.04 is required to build wheels
        # compatible with older default gcc.
        os: [ubuntu-20.04, ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1

      - name: Checkout submodules
        run: git submodule update --init --recursive --depth=1

      - name: Set up Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Use frozen pip version
        run: |
          pip install --constraint=.github/constraints.txt pip
          pip --version

      - name: Install poetry
        run: |
          pip install --constraint=.github/constraints.txt poetry
          poetry --version
          poetry version

      - name: Build wheel
        run: |
          poetry build -f wheel

      - name: Build sdist
        run:  poetry build -f sdist
        if:   matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'

      - name: Publish package for ${{ matrix.os }}, python ${{ matrix.python-version }}
        run:  poetry publish  -u __token__ -p ${{ secrets.PYPI_TOKEN }}
