name: Release

env:
  PYTHON_VERSION: '3.9'

on:
  push:
    branches:
      - main
      - master

defaults:
  run:
    shell: bash

jobs:

  release-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Checkout submodules
        run: git submodule update --init --recursive --depth=1

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64


      - name: Use frozen pip version
        run: |
          pip install --constraint=.github/constraints.txt pip
          pip --version

      - name: Install poetry
        run: |
          pip install --constraint=.github/constraints.txt poetry
          poetry --version
          poetry check
          poetry version

      - name: Install Nox
        run: |
          pip install --constraint=.github/constraints.txt nox nox-poetry
          nox --version
# TODO: uncomment when finish debugging Release action
#      - name: Run nox tests
#        run: nox --no-color --python ${{ env.PYTHON_VERSION }}

  release:
    needs: release-tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2    # need previous revision to define tag

#      - name: Set up Python
#        uses: actions/setup-python@v1
#        with:
#          python-version: ${{ env.PYTHON_VERSION }}
#
#      - name: Upgrade pip
#        run: |
#          pip install --constraint=.github/constraints.txt pip
#          pip --version
#
#      - name: Install poetry
#        run: |
#          pip install --constraint=.github/constraints.txt poetry
#          poetry --version
#          poetry check
#          poetry version

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "::set-output name=sha::$(git rev-parse --verify --quiet HEAD^)"

      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: |
            poetry version --short | sed "s/-.*$//g"

#      - name: Bump version for developmental release
#        if: "! steps.check-version.outputs.tag"
#        run: |
#          poetry version patch &&
#          version=$(poetry version --short) &&
#          poetry version $version.dev.$(date +%s)

#      - name: Install dependencies before build
#        run: |
#          poetry install --no-dev
#
#      - name: Build package
#        run: |
#          poetry build --ansi

#      - name: Publish package on PyPI
#        if: steps.check-version.outputs.tag
#        uses: pypa/gh-action-pypi-publish@v1
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_TOKEN }}
#
#      - name: Publish package on TestPyPI
#        if: "! steps.check-version.outputs.tag"
#        uses: pypa/gh-action-pypi-publish@v1
#        with:
#          user: __token__
#          password: ${{ secrets.TEST_PYPI_TOKEN }}
#          repository_url: https://test.pypi.org/legacy/

      - name: Publish the release notes
        uses: release-drafter/release-drafter@v5
        with:
          publish: ${{ steps.check-version.outputs.tag != '' }}
          tag: ${{ steps.check-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.MCKIT_GITHUB_TOKEN }}
