name: Release
on:
  push:
    tags:
      - '*.*.*'
jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9']
        exclude:
          - os: windows-latest
            python-version: 3.7   # py37 on Windows takes too much, and it wants nlopt.dll
    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: tag
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install nox and poetry
      run: |
        set -e
        python -m ensurepip
        python -m install -U pip
        pip install nox==2020.12.31
        pip install poetry==1.1.4
    - name: Checkout submodules
      run: git submodule update --init --recursive --depth=1
    - run: nox -s tests -p ${{ matrix.python-version }}
    - name: Set version
      run: |
        printf 'Tag version:    %s\n' ${{ steps.tag.outputs.tag }}
        printf 'Branch version: %s\n' $(poetry version --short)
        poetry version ${{ steps.tag.outputs.tag }}
    - run: poetry install --no-dev
    - run: poetry build
    - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
