name: TestPyPI
on:
  push:
    branches:
      - master
jobs:
  test_pypi:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9']
        exclude:
          - os: windows-latest
            python-version: 3.7   # py37 on Windows takes too much, and it wants nlopt.dll
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: x64
    - run: pip install poetry==1.1.4
    - run: >-
        poetry version patch &&
        version=$(poetry version | awk '{print $2}') &&
        poetry version $version.dev.$(date +%s)
    - name: Checkout submodules
      run: git submodule update --init --recursive --depth=1
    - run: poetry install --no-dev
    - run: poetry build
    - uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
