name: Tests MacOS compatibility

# Temporary (?) action to check if MKL is compatible with the recent macos
# If passed return to tests.yml

on:
  push:
    branches:
      - "devel"
    paths:
      - "**.py"
      - "**.c"
      - "**.h"
      - "**.yaml"
      - "**.yml"
      - "**.toml"
      - "**/data/**"
      - ".github/constraints.txt"
      - "!adhoc/**"
      - "!tools/**"


concurrency:
  group: ci-test-macos-${{ github.ref }}-1
  cancel-in-progress: true

jobs:

  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # TODO dvp: check https://github.com/MC-kit/mckit/issues/228 on macos
        os: [macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 1

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive --depth=1

      - uses: actions/setup-python@v4.4.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Use frozen pip version
        run: |
          pip install --constraint=.github/constraints.txt pip virtualenv
          pip --version

      - name: Install nox
        run: |
          pip install --constraint=.github/constraints.txt nox
          nox --version

      - name: Load poetry cache
        id: cached-poetry-dependencies
        uses: actions/cache@v3.2.3
        with:
          path: |
            .cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        run: |
          pip install --constraint=.github/constraints.txt poetry
          poetry --version
          poetry config --local cache-dir .cache/pypoetry
          poetry config --local virtualenvs.create false
          poetry env info

      - name: Check if pip can install MKL
        run: |
          pip install mkl-devel

      - name: Check if poetry finds MKL
        run: |
          poetry search mkl-devel

      - name: Run nox tests
        run: nox  --force-color --session tests --python ${{ matrix.python-version }}
