name: "MCKit Tests"

on:
  push:
    branches: ["master", "devel"]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9']
        exclude:
          - os: windows-latest
          - python-version: 3.7   # py37 on Windows takes too much, and it wants nlopt.dll
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Checkout submodules
        run: git submodule update --init --recursive --depth=1
      - name: Install nox
        run: pip install nox==2020.8.22
      - name: Install poetry
        run: pip install poetry==1.1.4
      - name: Run nox safety tests
        run: nox -s safety -p ${{ matrix.python-version }}
        if: matrix.python-version == '3.9'    # the version is restricted in noxfile.py
      - name: Run nox tests
        run: nox -s tests -p ${{ matrix.python-version }}
