name: Tests

on:
  push:
    branches:
      - "master"
      - "devel"
      - "main"
    paths:
      - "**.py"
      - "**.c"
      - "**.h"
      - "**.yaml"
      - "**.yml"
      - "**.toml"
      - "!adhoc/**"
      - "!scripts/**"
  pull_request:
    branches:
      - "master"
      - "devel"
      - "main"
    paths:
      - "**.py"
      - "**.c"
      - "**.h"
      - "**.yaml"
      - "**.yml"
      - "**.toml"
      - "!adhoc/**"
      - "!scripts/**"

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    if: |
      !contains(github.event.head_commit.message, '[skip_ci]')
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Checkout submodules
        run: git submodule update --init --recursive --depth=1

      # TODO(ci) dvp: check v3 - libnlopt not found...
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Use frozen pip version
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version
          poetry check
          poetry version
          poetry env info

#      - name: Install self
#        run: |
#          poetry install --no-dev
#
#      - name: Build the wheel
#        run: |
#          poetry build --format wheel

      - name: Install nox and nox-poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt nox nox-poetry
          nox --version

      - name: Run nox tests
        run: nox  --no-color --python ${{ matrix.python-version }}

      - name: Upload coverage data
        uses: "actions/upload-artifact@v3"
        with:
          name: coverage-data
          path: ".coverage.*"

      - name: Build documentations
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'
        run:  nox -s docs-build --no-color --python ${{ matrix.python-version }}

      - name: Upload documentation
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/_build

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Use frozen pip version
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Install Nox
        run: |
          pip  install --constraint=.github/workflows/constraints.txt nox nox-poetry
          nox --version

      - name: Download coverage data
        uses: actions/download-artifact@v3
        with:
          name: coverage-data

      - name: Combine coverage data and display human readable report
        run: |
          nox --no-color --session=coverage

      - name: Create coverage report
        run: |
          nox --no-color --session=coverage -- xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v2.1.0
